"""create all tables

Revision ID: fdf2f348982b
Revises: ff5f87b144b3
Create Date: 2022-08-05 12:32:49.239410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf2f348982b'
down_revision = 'ff5f87b144b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=140), nullable=False),
    sa.Column('data_created', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_articles')
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    op.create_table('user_articles',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('user_articles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='user_articles_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_articles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_articles_pkey')
    )
    op.drop_table('article_comments')
    # ### end Alembic commands ###
